In [1]:
pip install numpy==1.26

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
np.__version__

'1.26.0'

In [5]:
a = np.array([(13, 54, 23)])

In [6]:
a

array([[13, 54, 23]])

In [11]:
list = [23, 3.94, True, "yyy"]

In [22]:
A = np.array([("xxx", True, 790.00), (38, 20, 2), (8, 49, 9.94)])

In [23]:
A

array([['xxx', 'True', '790.0'],
       ['38', '20', '2'],
       ['8', '49', '9.94']], dtype='<U32')

In [24]:
print(A)

[['xxx' 'True' '790.0']
 ['38' '20' '2']
 ['8' '49' '9.94']]


In [27]:
A[0][1] = 1
A = np.transpose(A)


In [29]:
A.shape
A.size

9

In [34]:
Az = np.ravel(A)
A

array(['xxx', '38', '8', '1', '20', '49', '790.0', '2', '9.94'],
      dtype='<U32')

In [47]:
A.reshape(3,3)

array([['xxx', '38', '8'],
       ['1', '20', '49'],
       ['790.0', '2', '9.94']], dtype='<U32')

In [44]:
zeros = np.zeros((3,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [38]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])